### ISSUE TITLE
Ligne incorrecte dans la fonction isPassword() du fichier class.Utilisateur.php

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#10]
Puisque cette fonction n’a qu’une ligne, tout est dit. Cette fonction doit renvoyer un booléen, c’est bien ça ? Si oui, il semblerait qu’on ne peut pas le faire comme cela.

**Comment by flowerkinzy** [comment]
C'est une histoire de $this->nom_attribut.
