### ISSUE TITLE
Le test du code ?

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#13]
Vous faites comment pour tester votre code ? Je veux dire, il existe des sites où on peut vérifier la syntaxe du code, mais pour vérifier qu'il fait bien ce que l'on veut, on est obligé de le tester sur notre appli, mais pour l'instant c'est compliqué de tester si telle méthode fait bien ce qu'elle veut, non ? Vous faîtes comment vous ?

**Comment by VeryTastyTomato** [comment]
Je teste pas.

**Comment by flowerkinzy** [comment]
moi, j'ai un fichier index.html où j'ai testé les méthodes de personne et utilisateur.

Récemment, ça ressemblait à ça:

<?php
ini_set('display_errors', 1); 
error_reporting(E_ALL);
  echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">';
  echo '
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Tests GaliDAV</title></head><body> <h1>Test class personne</h1>';


require_once("class.Personne.php");
require_once("class.Utilisateur.php");
$P=new Personne("KAPGNEP","Flora");
$P->setEmailAddress1("flora.kapgnep@gmail.com");
$P->addStatus(new Statut_personne(Statut_personne::ADMINISTRATOR));
$P->addStatus(new Statut_personne(Statut_personne::STUDENT));
$P->addStatus(new Statut_personne(Statut_personne::HEAD));

$Ptext=$P->toHTML();
$U=Utilisateur::convertPersonToUser($P,"Flowerkinzy","mdp");
$Utext=$U->toHTML();



echo 
"<div> $Ptext</div>$Utext</body>
</html>";
	

?>

**Comment by flowerkinzy** [comment]
LE copier -coller interprète direct les balises, d'où le résultat

**Comment by LilTiti** [comment]
Désolé mais j'ai pas compris ton dernier commentaire. 
Et le test que tu viens de poster, sur ton navigateur il met quoi ?

**Comment by flowerkinzy** [comment]
Quand j'ai voulu copier le code ici, les echo() avec de l'html dedans, il me les a affichés comme dans un navigateur.
Et sinon, voilà le résultat
![capture du 2015-03-24 10 45 51](https://cloud.githubusercontent.com/assets/8625370/6799049/f911efa8-d212-11e4-84e9-aa010e91f06f.png)

**Comment by flowerkinzy** [comment]
Jai créé unee personne P, changer son mail, ajouter des statuts. J'ai sauvegardé le resultat de P->to_html() dans Ptext puis j'ai converti cette personne en utilisateur U (+ID/mdp) et j'ai fait de même.

A la fin, j'ai affiché Ptext et Utext

**Comment by flowerkinzy** [comment]
Voilà le screenshot de mon fichier
![capture du 2015-03-24 10 48 57](https://cloud.githubusercontent.com/assets/8625370/6799114/6bde6d2c-d213-11e4-8e67-f924d737082b.png)

**Comment by LilTiti** [comment]
Ok merci je clos cette issue !
