### ISSUE TITLE
Doc + méthodes de la classe Cours

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#14]
Je soulève 2-3 petites questions en 1 issue mais elles vont ếtre résolues rapidement donc je me le permet : 
1) Concernant la doc, ya un "Class.txt" et un "Class_MD" : what's the diference ? 
2) Concernant la classe "Cours" : 
   2-1) je vois dans la doc que y'a un "WTF?" pour la méthode "retire()", je m'explique : il y a de base une méthode "retirer()" dans cette classe (je suppose pour supprimer un cours de l'EDT), je l'avais mis en anglais, mais je vous l'accorde c'était une traduction digne d'un magnifique 250 au TOEIC. Un "revoke" ou "delete" aurait été mieux.
   2-2) j'ai posé une question concernant la méthode "Cours(matière, begin, end)" mais je pense qu'y répondre ici reste plus pratique qu'un commentaire dans le code. Si ce n'est pas un constructeur (ce dont je doutais connaissant l'existence de "__construct()"), à quoi sert cette méthode ?

**Comment by LilTiti** [comment]
2-1) en fait je vois que le nom "retire" a déjà été remplacé par "remove". J'ai MAJ la doc avec "remove" du coup ;)

**Comment by flowerkinzy** [comment]
1) Class.rxr est un premier essai de Simon basé sur le CdC, mais c'est class_MD qu'il faut considérer
