### ISSUE TITLE
TODO 1: PHP - Création d'un utilisateur/calendrier dans la base postgresql

### ISSUE THREAD

**Issue by flowerkinzy** [VeryTastyTomato/GaliDAV#15]
Tout est dans le titre

**Comment by Orni2Thorinque** [comment]
Vos installations de PHP vous permet d'intervenir sur Postgres? ça vous donne quoi phpinfo()?

**Comment by flowerkinzy** [comment]
Euh, tas pas besoin de PHP pour utiliser postgre. Et cette issue est reliée à mes 2 derniers commits
