### ISSUE TITLE
Erreurs de syntaxe dans les classes BaseDeDonnees, Personne et Utilisateur

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#24]
@flowerkinzy Ça vient de tes modifs. Et n’oublie pas qu’on ne peut déclarer plusieurs constructeurs dans PHP (*PHP Code Checker* n’aime pas en tout cas). N’hésitez pas à vérifier vos modifs sur ce site avant de faire un *push*.

**Comment by flowerkinzy** [comment]
modifié entre temps, je push bientôt
