### ISSUE TITLE
Paramètre manquant dans modifyClass() de class.Administrateur ?

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#25]
Si je veux modifier la classe, et que cela correspond selon l’opération à un ajout ou à une suppression d’un étudiant de cette classe, encore faut-il que je sache lequel. Or l’étudiant à ajouter ou supprimer n’est pas la liste des paramètres de la méthode.

**Comment by flowerkinzy** [comment]
Tu as raison, un 3ème paramètre serait bien utile (En le mettant à null par défaut si jamais, il ne sert pas pour d'autres opérations non encore imaginées)

**Comment by VeryTastyTomato** [comment]
Du coup je ferais pareil pour d’autres méthodes (par exemple pour la méthode *modifyGroup_Members()*, il manque le groupe dans lequel je veux ajouter ou supprimer un étudiant).

**Comment by flowerkinzy** [comment]
Très bien.
