### ISSUE TITLE
Pas compris le TODO de modifyClass_CoursesModel() de class.Responsable

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#26]
Il n’y a pas de maquette dans la classe Classe. À moins que ce ne soit une association à rajouter ? Mais dans ce cas c’est pas une liste mais seulement 1 maquette ?

**Comment by flowerkinzy** [comment]
Non, ca fait partie de ce qui manque. En effet, 1 maquette que jai traduit par CoursesModel

**Comment by VeryTastyTomato** [comment]
D’accord, mais du coup je ne comprends pas pourquoi la méthode en question a tant de paramètres.

**Comment by flowerkinzy** [comment]
une maquette est composée d'éléments de maquette et un élément de maquette est composé des param de la fonction (matiere, type,nb_heures)

**Comment by VeryTastyTomato** [comment]
Ok. Mais dans ce cas se pose un autre problème : quel élément de maquette modifié ? Les paramètres de la méthode ne l’indiquent pas, du coup on ne peut savoir quel élément de maquette modifié dans la liste des éléments de maquette de la maquette de la classe donnée en paramètre de modifyClass_CoursesModel() de class.Responsable.

**Comment by flowerkinzy** [comment]
Je t'ai répondu en live. Par contre, tu peux rajouter une opération: new, modify, remove

**Comment by VeryTastyTomato** [comment]
Ouais, mais j’ai oublié ce que tu m’as dit… Désolé mais tu peux repréciser ? Quand aux opérations, tu veux dire celles qui sont indiqué par la variable $operation ? Dois-je rajouter ces nouvelles opérations dans toutes les méthodes où apparaît la variable $operation ?

**Comment by flowerkinzy** [comment]
Heu en gros, les paramètre sont uniques par élément de maquette. Un élément de maquette est unique (matière, type de cours) et a une valeur qui peut changer (NB heures). Avec le paramètre $operation, on indique si on veut supprimer modifier un élément de la maquette de la classe.

Pas pigé ta dernière question

**Comment by VeryTastyTomato** [comment]
Tu as dit de rajouter de nouvelles opérations : new, modify et remove (cela veut bien dire que le paramètre $operation peut prendre les valeurs 'new', 'modify', et 'remove' n’est-ce pas ?), mais il n’y a pas que la méthode *modifyClass_CoursesModel()* qui a ce paramètre, d’autres méthodes ont aussi un paramètre $operation (comme dans une des méthodes de classe Administrateur).

**Comment by VeryTastyTomato** [comment]
D’ailleurs j’y pense, puisque ces paramètres permettent d’identifier un élément de maquette, pourquoi ne pas plutôt passer en paramètre un élément de maquette (un objet de type Element_maquette) ?

**Comment by flowerkinzy** [comment]
Oui c ça, mais il n'y a pas ces 3 opérations dans tous les cas, faut s'adapter.

Oui tu peux passer un élément de maquette (et une opération) en paramètre
