### ISSUE TITLE
Une BDD unique ?

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#28]
On utilise une seule et unique BDD pour toute l'appli ? Je pose cette question car on a déjà une BDD agendav, une BDD davical, et on avait créé pour nos tests sur les user une BDD galidav. Mais la finalité c'est d'avoir une base avec tous les users, les EDT etc... Car j'ai fait le template de la génération de PDF, j'ai besoin maintenant de récupérer des EDT depuis la BDD pour afficher des "vrais" EDT, faire mes tests etc... Du coup sur quelle BDD sera établie notre appli ? I don't know if I'm understandable...

**Comment by flowerkinzy** [comment]
Notre appli a besoin dagendav davical et no's données.
Par contre, Les calendriers don't surement stocked Dans davical (db ou fichier, je ne sais pas)
