### ISSUE TITLE
Constructeur de "Cours"

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#30]
Dans le constructeur de la classe "Cours" quelqu'un a rajouté des tests concernant les heures passées en paramètres. Ce que j'approuve, seulement on test si ce sont des entiers, pourquoi donc ? Car je suis en train d'effectuer des tests d'automatisation de mon PDF, je crée des variables de type "date" en paramètre que je souhaite récupérer ensuite dans ma création de PDF, sauf que vu que ce ne sont pas des entiers il me met la date et l'heure d'aujourd'hui lors de la création d'un cours. J'aimerais du coup modifier ces tests pour vérifier plutôt si ce sont des dates, mais je préfère demander s'il y a une raison particulière à regarder si ce sont des entiers (alors qu'on est censé avoir des dates).

**Comment by VeryTastyTomato** [comment]
Vazy mec, vire-moi ces tests et fais-toi plez.

**Comment by flowerkinzy** [comment]
C pas moi qui est fait ces tests mais y'a un format date dans PHP et cest ce format (c un entier universel)

**Comment by LilTiti** [comment]
On garde ces tests du coup, vu qu'on manipule pas les DateTime.
