### ISSUE TITLE
Nouvel attribut dans "EDTClasse"

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#31]
J'ai ajouté un attribut "classe" dans "EDTClasse" (et son getter) pour savoir à quelle classe appartient l'EDT en question (vu qu'il ne doit être lié qu'à une classe). Moi ça me permet de mettre automatiquement le titre de l'EDT dans le PDF, mais ça peut avoir d'autres utilités.
Le but de cette issue est juste de savoir si vous n'êtes pas de mon avis, je la fermerai demain soir s'il n'y a pas d'avis contraire.

**Comment by flowerkinzy** [comment]
Pas d'opposition mais sachez que pour chaque attribut créé, faut un accesseur qui fasse plusieurs requêtes SQL. (Cf classe personne à titre d'exemple) et c chiant.


Dc accéder à cet attribut, c faire un chargement de la bdd vers un objet classe (cf loadfrombdd de la classe personne/utilisateur)

**Comment by LilTiti** [comment]
Je m'en doute bien, mais je pense que ça peut être pratique de savoir à quelle classe appartient cet EDTClasse, c'est le but d'avoir créé cette classe héritant de EDT je pense...

**Comment by flowerkinzy** [comment]
@LilTiti
Stp, change ce que tu voulais faire pour mettre un attribut groupe dans EDT. La base est construite pareil pour les classes et groupes

**Comment by LilTiti** [comment]
Dans "EDT" ou "EDTClasse" ?

**Comment by flowerkinzy** [comment]
Dans EDT (dsl javais pas vu).

**Comment by flowerkinzy** [comment]
Je l'ai fait par moi-même dans la classe EDT. (attribut groupe) Jai aussi ajouté un attribut subject (cf commentaires)
