### ISSUE TITLE
Type date

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#32]
En changeant le constructeur de "Cours" j'ai remarqué une chose : toutes les dates manipulées sont de "l'ancien" type "date" (qui est un timestamp je crois), or il existe un objet "DateTime" qui est, semble-t-il, plus facile à manipuler. Du coup j'ai commencé à modifier les dates à plusieurs endroits (notemment dans les getters de date->string) pour manipuler des objets DateTime, mais avant de tout modifier (puis de push), il faut que je sois sûr que tout le monde est OK pour manipuler des DateTime plutôt que des timestamp.

**Comment by flowerkinzy** [comment]
En fait, dans la bdd, c de type timestamp...
Mais en quoi c plus facile?

**Comment by LilTiti** [comment]
Pour toutes les opérations sur les dates apparemment. Par exemple, avec un timestamp il me semble que 14/03/2015 > 12/04/2015 (car 14>12). Mais bon pour notre utilisation je ne suis pas sûr que ça aie une grande influence, et il est vrai que comme SQL est resté avec les timestamp, ça risque de nous faire galérer plutôt qu'autre chose. Donc on garde les timestamp, tant pis pour les DateTime, j'ai bien fait de ne rien commit.
