### ISSUE TITLE
Gestion BDD de l'appli

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#33]
Alors moi j'ai un problème pour mon PDF, pour les tests j'ai créé manuellement des instances d'objets, mais il faut que je passe directement par l'appli pour les tests sinon je ne peux pas aller plus loin. Alors comment fait-on le lien entre l'appli et nos données perso. Exemple : je créé un calendrier "algo" sur agendav, pour tous les cours d'algo, comment je fais pour créer une instance de Matière dans nos données et ainsi la manipuler dans toutes nos méthodes ? Pour moi, c'est le plus gros à faire, vu qu'il reste plusieurs méthodes à faire en attente de BDD, donc de lien entre l'appli et nos données je pense...

**Comment by flowerkinzy** [comment]
C'est justement mon PB: voir mon issue.
J'ai voulu inclure une classe perso dans les files dagendav. Rien a faire, ça râle.

La manipulation de la table gsubject à partir de la classe matière est à coder quoi qu'il en soit

**Comment by flowerkinzy** [comment]
cf 
TODO 10 https://github.com/VeryTastyTomato/GaliDAV/issues/37
