### ISSUE TITLE
Problème de conflits dans class.EDT.php et class.EDTClasse.php

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#35]
@flowerkinzy J’ai pas compris tes modifs dans ces deux fichiers, dans EDTClasse tu donnes en paramètre du constructeur une instance de Classe, mais dans EDT tu attends un Object, qui est supposé être un Groupe ou une Matière.

**Comment by LilTiti** [comment]
A la base, c'est moi qui avait fait le constructeur de EDTClasse en passant une Classe en paramètre. Mais de toute façon, une Classe est un Groupe, alors est-ce que cela pose un problème ?

**Comment by flowerkinzy** [comment]
Une Classe est un groupe donc il n'y a pas conflit en tant que tel.
Cela dit, étant donné que les matières ont leur calendrier, j'ai permis qu'en paramètre d'un edt, il y ait une matière
