### ISSUE TITLE
"removeFromDB" de Personne

### ISSUE THREAD

**Issue by LilTiti** [VeryTastyTomato/GaliDAV#47]
J'ai 2 questions concernant cette méthode : 
1) Est-ce normal qu'on tente de supprimer la personne de la table de Statut_personne 2 fois ? (une dès le début, une autre à la fin)

2) Le premier select teste si la personne est un utilisateur (ou plus précisément un enseignant). Pourquoi on tente de le supprimer d'une matière avant le "if" qui regarde si c'est un utilisateur ou pas ? Vu que cette partie est en commentaire à l'intérieur du if je me dis que y'a une bonne raison, mais je vois pas.

**Comment by flowerkinzy** [comment]
1-non
2- pcq une matière est relié à 3 intervenants (speakers) qui sont des personnes et pas forcément des users

**Comment by LilTiti** [comment]
C'est bon c'est revenu. 
1) j'ai vu que t'as corrigé
2) ah oui c'est vrai que certains enseignants peuvent ne pas être utilisateurs, exact !
