### ISSUE TITLE
Modélisation: classe Personne

### ISSUE THREAD

**Issue by flowerkinzy** [VeryTastyTomato/GaliDAV#5]
@VeryTastyTomato : j'avais dit 'pas les classes héritant de personne' pcq elles apparaissent sur mon diagramme. 

De plus, pourquoi un array supplémentaire? (question sincère) -> Pcq Simon est censé faire un pseudo-type StatutPersonne (et je lui ai dit aujourd'hui de ne pas faire un array)

**Comment by VeryTastyTomato** [comment]
Quelles classes héritent de la classe Personne ? Je n’en vois aucune. De toute façon, j’avais oublié cela au temps pour moi (en fait je ne m’en souviens même pas).

En ce qui concerne le tableau, c’est Simon qui l’a ajouté dans son *Pull request*. C’est vrai que j’ai pas fait gaffe à ce fait lorsque j’ai fusionné les branches.

**Comment by flowerkinzy** [comment]
Bon ok, il a vraiment pas regardé les fichiers alors...
Pcq si tu as fini, questce que tu as fais exactement alors @Orni2Thorinque ? (Parce que les fichiers StatutPersonne et autres sont vides...)

**Comment by LilTiti** [comment]
Je suis un peu perdu en rentrant de l'entraînement là...
Alors si je comprends bien tous (enfin peut-être pas tous, mais beaucoup) de fichiers php ont été créés sur le même modèle. Mais les trucs en commentaire illisibles je comprends que dalle. Et Simon dire "wesh" quand tu fais un commit c'est pas fait pour m'aider ça...
Et qui a touché aux méthodes de mes classes EDT ? J'avais déjà pas grand chose à faire (enfin ça je l'avais fait)...

**Comment by flowerkinzy** [comment]
@LilTiti : Euh... sur le git, ya pas de trace que t'y as touché. Moi pour ma part j'ai rajouté un comm TODO pour la suite. Les commentaires illisbles cherche pas à comprendre, cest rien.

**Comment by LilTiti** [comment]
@flowerkinzy : non je n'avais pas commité, je disais juste que je l'avais fait chez moi ce matin. Oui mais le TODO pour l'instant, je peux pas faire grand chose... En gros là j'ai juste à rajouter les attributs de EDT... Am I wrong ?

**Comment by flowerkinzy** [comment]
@LilTiti : Les attributs (qui appellent dautres classes) et les accesseurs nécessaires.
Mais comme t'as dit que qlqn a touché, jai pas compris...

**Comment by LilTiti** [comment]
@flowerkinzy : oui mais je voulais dire : quelqu'un a fait mon boulot x) enfin une partie vu que ce n'était que la déclaration des méthodes.

**Comment by flowerkinzy** [comment]
@LilTiti : C'est le code auto-généré (ce qui explime les comms illisibles)

**Comment by LilTiti** [comment]
@flowerkinzy : Ah au temps pour moi je savais pas !

**Comment by VeryTastyTomato** [comment]
Les fichiers et commentaires *incompréhensibles* ont été généré par ArgoUML de flowerkinzy. Ce qu’on avait à faire pour l’instant c’est écrire les accesseurs et mutateurs (avec éventuellement les vérifs nécessaires pour les paramètres) et régler les portées des attributs d’instance (genre mettre *private* au lieu de *public*).
