### ISSUE TITLE
Nettoyer le code

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#6]
Virer les commentaires inutiles, renommer les variables en anglais, et partir une bonne fois pour toute sur des fichiers propres.

**Comment by LilTiti** [comment]
Qu'appelles tu fichier propre ?
Et perso hier soir j'ai tout mis en anglais (sauf les noms de classe évidemment). Il faut que j'enlève tous les commentaires inutiles. Mais poste un "modèle" de fichier propre, comme ça on fera tous exactement la même chose.

**Comment by VeryTastyTomato** [comment]
Bah je vais nettoyer tous les fichiers de toute façon, donc vous pourrez voir. Je pense qu’il faudrait aussi changer le nom des fichiers et les mettre en anglais, mais ce serait peut-être mieux à la fin.

**Comment by VeryTastyTomato** [comment]
J’ai enfin terminé la réécriture de code. Ça devrait marcher sur vos machines aussi (en faisant attention aux noms de domaine que vous avez utilisé).
