### ISSUE TITLE
Bug dans class.Administrateur.php : opération ajouterUtilisateur

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#7]
Il y a deux fois l’opération **ajouterUtilisateur()**, avec des paramètres certes différents, mais il semblerait que contrairement à Java ou C++, PHP ne permet pas ce genre de choses. J’ai testé le code (en copiant-collant) sur ce site : http://phpcodechecker.com/index.htm

**Comment by flowerkinzy** [comment]
Corrigé dans le fichier concerné
