### ISSUE TITLE
Bug dans la classe Cours : attributs begin et end

### ISSUE THREAD

**Issue by VeryTastyTomato** [VeryTastyTomato/GaliDAV#8]
Il semblerait que la syntaxe ne soit pas bonne, avec les crochets ou les barres verticales, mais je ne sais pas quelles corrections appliquées pour l’instant.

**Comment by flowerkinzy** [comment]
La syntaxe est celle d'ArgoUML pour le format Date. A changer
@LilTiti et @VeryTastyTomato : Il faut s'assurer de faire les attributs présents dans une classe mais aussi ceux représentés par des flèches (considérées comme des associtiations. Exemple: Un cours est relié à une liste d'EDTs(1 ou +) et vice-versa
